before:
  hooks:
    - go mod tidy
    - go test ./...
    - ./scripts/completions.sh
builds:
  - binary: safebox
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: 'checksums.txt'

archives:
  - format: 'binary'
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: safebox
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "A Fast and Flexible secret manager built with love by adikari in Go."
    license: "MIT"
    test: |
      system "#{bin}/safebox --version"
    install: |
      bin.install "safebox"
      bash_completion.install "completions/safebox.bash" => "safebox"
      zsh_completion.install "completions/safebox.zsh" => "_safebox"
      fish_completion.install "completions/safebox.fish"
    repository:
      owner: adikari
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - id: safebox
    package_name: safebox
    maintainer: Adikari <me@subash.com.au>
    description: "A Fast and Flexible secret manager built with love by adikari in Go."
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
    contents:
    - src: ./completions/safebox.bash
      dst: /usr/share/bash-completion/completions/safebox
      file_info:
        mode: 0644
    - src: ./completions/safebox.fish
      dst: /usr/share/fish/vendor_completions.d/safebox.fish
      file_info:
        mode: 0644
    - src: ./completions/safebox.zsh
      dst:  /usr/share/zsh/vendor-completions/_safebox
      file_info:
        mode: 0644

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
