before:
  hooks:
    - go mod tidy
    - go test ./...
    - ./scripts/completions.sh
builds:
  - binary: safebox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: 'checksums.txt'

archives:
  - files:
      - completions/*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: safebox
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "A Fast and Flexible secret manager built with love by adikari in Go."
    license: "MIT"
    test: |
      system "#{bin}/safebox --version"
    install: |
      bin.install "safebox"
      bash_completion.install "completions/safebox.bash" => "safebox"
      zsh_completion.install "completions/safebox.zsh" => "_safebox"
      fish_completion.install "completions/safebox.fish"
    tap:
      owner: adikari
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
