# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safebox < Formula
  desc "A Fast and Flexible secret manager built with love by adikari in Go."
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adikari/safebox/releases/download/v1.0.0/safebox_1.0.0_darwin_amd64.tar.gz"
      sha256 "108b1f9aa03da766fcf1d3160b9030ee25c6e9bbb3aaf23ab63caa146afbbda1"

      def install
        bin.install "safebox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adikari/safebox/releases/download/v1.0.0/safebox_1.0.0_darwin_arm64.tar.gz"
      sha256 "7643fd0b9dfc4bd0000c64c0abe51dcf4dc89a0a8d6aa42ffb519582c28c3318"

      def install
        bin.install "safebox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adikari/safebox/releases/download/v1.0.0/safebox_1.0.0_linux_arm64.tar.gz"
      sha256 "a1a88a2a78ca9f6346edf0ed8a6f832d5a8e6b559968927aad92c1c2d9cf9c5a"

      def install
        bin.install "safebox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adikari/safebox/releases/download/v1.0.0/safebox_1.0.0_linux_amd64.tar.gz"
      sha256 "a5159e6b6edb6a3911a08328d47394e3924f9bc73a9b9deb583fd9eb6a24e256"

      def install
        bin.install "safebox"
      end
    end
  end

  test do
    system "#{bin}/safebox --version"
  end
end
